openapi: 3.0.0
info:
  title: Transaction API
  version: 1.0.0
  description: API for managing transactions

servers:
  - url: http://localhost:4001/api/v1

tags:
  - name: Transactions
    description: Transaction management

paths:
  /transactions:
    post:
      summary: Create a new transaction
      tags:
        - Transactions
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionInput'
      responses:
        '201':
          description: Transaction created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'

    get:
      summary: Get all transactions
      tags:
        - Transactions
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            example: 1
        - in: query
          name: limit
          schema:
            type: integer
            example: 10
        - in: query
          name: category
          schema:
            type: string
            example: bills
        - in: query
          name: sortBy
          schema:
            type: string
            example: amount
        - in: query
          name: sortOrder
          schema:
            type: string
            enum: [asc, desc]
            example: desc
      responses:
        '200':
          description: Paginated list of transactions
          content:
            application/json:
              schema:
                type: object
                properties:
                  docs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
                  totalDocs:
                    type: integer
                  limit:
                    type: integer
                  page:
                    type: integer
                  totalPages:
                    type: integer
                  hasNextPage:
                    type: boolean
                  hasPrevPage:
                    type: boolean


  /transactions/{id}:
    get:
      summary: Get a transaction by ID
      tags:
        - Transactions
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Transaction detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'

    put:
      summary: Update a transaction by ID
      tags:
        - Transactions
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionUpdate'
      responses:
        '200':
          description: Transaction updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'

    delete:
      summary: Delete a transaction by ID
      tags:
        - Transactions
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Transaction deleted

  /transactions/monthly:
    get:
      summary: Get monthly transactions
      tags:
        - Transactions
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: month
          required: false
          schema:
            type: integer
            example: 1
        - in: query
          name: year
          required: false
          schema:
            type: integer
            example: 2026
      responses:
        '200':
          description: Monthly transaction summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionMonthlyResponse'

 
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Transaction:
      type: object
      properties:
        _id:
          type: string
        user:
          type: string
        amount:
          type: number
        category:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    TransactionInput:
      type: object
      required:
        - amount
        - category
      properties:
        amount:
          type: number
        category:
          type: string
        description:
          type: string

    TransactionUpdate:
      type: object
      properties:
        amount:
          type: number
        category:
          type: string
        description:
          type: string

    TransactionMonthlyResponse:
      type: object
      properties:
        total:
          type: number
        month:
          type: string
        year:
          type: number
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'