openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: API for user authentication

servers:
  - url: http://localhost:4001/api/v1

tags:
  - name: Auth
    description: User authentication

paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - Auth
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterInput'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: Validation or registration error

  /auth/login:
    post:
      summary: Login user
      tags:
        - Auth
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInput'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Invalid credentials

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RegisterInput:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string

    LoginInput:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string

    UserPublic:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string

    RegisterResponse:
      type: object
      properties:
        message:
          type: string
          example: User created successfully
        user:
          $ref: '#/components/schemas/UserPublic'

    LoginResponse:
      type: object
      properties:
        message:
          type: string
          example: User logged in successfully
        user:
          $ref: '#/components/schemas/UserPublic'
        token:
          type: string